#include "ssdv_codec.h"
#include <string.h>
#include "ssdv.h"

#define SSDV_FEED_CHUNK 128 // matches the reference tool's own feed granularity
#define SSDV_QUALITY 4 // 0-7, metadata recorded in packet header for the ground decoder's info -- SSDV doesn't iuse it to re-encode, since the input's already a JPEG

int ssdv_encode_image(
    const uint8_t *jpeg, 
    size_t jpeg_len, 
    const char *callsign, 
    uint8_t image_id, 
    uint8_t *out, 
    size_t out_cap, 
    size_t *out_len
) {
    ssdv_t ssdv;
    uint8_t pkt[SSDV_PKT_SIZE];

    if (ssdv_enc_init(&ssdv, SSDV_TYPE_NORMAL, (char *)callsign, image_id, SSDV_QUALITY, SSDV_PKT_SIZE) != SSDV_OK) {
        return -1;
    }
    ssdv_enc_set_buffer(&ssdv, pkt);

    size_t in_offset = 0;
    size_t written = 0;
    char c;

    // essentially keeps asking for encoded packets generated by SSDV. Stops if error or length done
    for(;;) {
        while ((c = ssdv_enc_get_packet(&ssdv)) == SSDV_FEED_ME) {
            size_t remaining = jpeg_len - in_offset;
            if (remaining == 0) break; /* premature EOF -- caught below */

            size_t chunk = remaining < SSDV_FEED_CHUNK ? remaining : SSDV_FEED_CHUNK;
            ssdv_enc_feed(&ssdv, (uint8_t *)(jpeg + in_offset), chunk);
            in_offset += chunk;
        }

        if (c == SSDV_EOI) break; /* whole image successfully packetized */
        if (c != SSDV_OK) return -1;

        if (written + SSDV_PKT_SIZE > out_cap) return -1;
        memcpy(out + written, pkt, SSDV_PKT_SIZE);
        written += SSDV_PKT_SIZE;
    }

    *out_len = written;
    return 0;
}